name: CI - Python (PyPA Sample)

on:
  workflow_dispatch:

jobs:
  python-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'   

      - name: Upgrade pip & install build/test tooling
        run: |
          python -m pip install --upgrade pip
          # 'build' creates sdist and wheel from pyproject.toml (PEP 517)
          pip install build
          # install test runner if you plan to add/keep tests
          pip install pytest

      
      
      - name: Build package (sdist & wheel)
        run: |
          python -m build
          mkdir -p staging
          cp dist/* staging/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Package
          path: staging
      - name: Setup java
        uses: actions/setup-java@v5.2.0
        with:
         distribution: 'temurin'
         java-version: '17'
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
         args: >
          -Dsonar.projectKey=bhuvana-cloud333_python-project
          -Dsonar.organization=bhuvana-cloud333
          -Dsonar.sources=src
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: https://sonarcloud.io/account/security
 
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 

         # ------------------ DOCKER LOGIN (AZURE) ------------------  
      - name: Docker login (Azure)
        uses: docker/login-action@v3
        with:
          registry: bhuvanaregistry.azurecr.io
          username: ${{ vars.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}    
  

          # ------------------ BUILD & PUSH IMAGE (MULTI-REGISTRY) ------------------
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |

            ${{ vars.AZURE_ACR_NAME }}.azurecr.io/python-project:latest
            ${{ vars.AZURE_ACR_NAME }}.azurecr.io/python-project:sha-${{ steps.tag-vars.outputs.short_sha }}
